// LOCALHOST
### Get all players
GET http://localhost:5500/players


### Get player by id
GET http://localhost:5500/players/674229e59e1b5d72a40c9310


### Create player
POST http://localhost:5500/players HTTP/1.1
content-type: application/json

{
    "firstName":"New Player",
    "lastName":"Gibb"
}


### PUT player
PUT http://localhost:5500/players/674229e59e1b5d72a40c9a30 HTTP/1.1
content-type: application/json

{
    "firstName":"Curtis",
    "lastName":"Gibb"
}
### DELETE player
DELETE http://localhost:5500/players/67422a209e1b5d72a40c9a32 HTTP/1.1

////////////////
// BOARDGAMES //
////////////////
### Get all boardgames
GET http://localhost:5500/boardgames


### Get boardgame by id
GET http://localhost:5500/boardgames/67426a31e732ba450ddf108bm


### Create boardgame
POST http://localhost:5500/boardgames HTTP/1.1
content-type: application/json

{
    "name":"Sample Game",
    "description":"Game description",
    "brand": "brand name",
    "numPlayers": "1-6",
    "ages": "8+",
    "playingTime": "60 mins",
    "yearCreated": "2010",
    "complexityRating": "3.5"
}


### PUT boardgame
PUT http://localhost:5500/boardgames/6742566ddda40700efbfa7b5 HTTP/1.1
content-type: application/json

{
    "name": "Settlers of America",
    "description": "fun",
    "brand": "brand here",
    "numPlayers": "3-4",
    "ages": "8+",
    "playingTime": "60 min",
    "yearCreated": "2000",
    "complexityRating": "3.5"
}
### DELETE baordgame
DELETE http://localhost:5500/boardgames/67426a31e732ba450ddf108b HTTP/1.1