// PRODUCTION
### Get all players
GET http://https://cse341-project2-psq1.onrender.com/players


### Get player by id
GET http://https://cse341-project2-psq1.onrender.com/players/67422a209e1b5d72a40c9a32


### Create player
POST http://https://cse341-project2-psq1.onrender.com/players HTTP/1.1
content-type: application/json

{
    "firstName":"Heather",
    "lastName":"Gibb"
}


### PUT player
PUT http://https://cse341-project2-psq1.onrender.com/players/674229e59e1b5d72a40c9a30 HTTP/1.1
content-type: application/json

{
    "firstName":"Curtis",
    "lastName":"Gibb"
}
### DELETE player
DELETE http://https://cse341-project2-psq1.onrender.com/players/67422a209e1b5d72a40c9a32 HTTP/1.1


### Get all boardgames
GET http://https://cse341-project2-psq1.onrender.com/boardgames


### Get boardgame by id
GET http://https://cse341-project2-psq1.onrender.com/boardgames/67422767b00f6f4f62b77e79


### Create boardgame
POST http://https://cse341-project2-psq1.onrender.com/boardgames HTTP/1.1
content-type: application/json

{
    "name":"New Game",
    "description":"Game description",
    "brand": "Brand",
    "numPlayers": "1-6",
    "ages": "8+",
    "playingTime": "60 mins",
    "yearCreated": "2010",
    "complexityRating": "2.6"
}


### PUT boardgame
PUT http://https://cse341-project2-psq1.onrender.com/boardgames/67422767b00f6f4f62b77e79 HTTP/1.1
content-type: application/json

{
    "name": "Settlers of America",
    "description": "fun",
    "brand": "brand here",
    "numPlayers": "3-4",
    "ages": "8+",
    "playingTime": "60 min",
    "yearCreated": "2000",
    "complexityRating": "3.5"
}
### DELETE baordgame
DELETE http://https://cse341-project2-psq1.onrender.com/boardgames/67415d008c20f869f259b4c6 HTTP/1.1